# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    # Most Cargo dependencies are shared with other Gecko components and their
    # versions must match mozilla-central. Only allow version updates for crates
    # that are exclusively used by neqo within Gecko. Security updates are
    # unaffected by this setting.
    # Verify against https://searchfox.org/mozilla-central/source/Cargo.lock
    allow:
      - dependency-name: "qlog"
      - dependency-name: "quinn-udp"
      - dependency-name: "enum-map"
      - dependency-name: "enumset"
    cooldown:
      default-days: 10
      semver-major-days: 20
      semver-minor-days: 10
      semver-patch-days: 5
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/actions/*"
      - "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 10
      # "semver" not supported for github-actions; see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#configuration-of-cooldown
      # semver-major-days: 20
      # semver-minor-days: 10
      # semver-patch-days: 5
  - package-ecosystem: "docker"
    directory: "/qns"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 10
      # "semver" not supported for docker; see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#configuration-of-cooldown
      # semver-major-days: 20
      # semver-minor-days: 10
      # semver-patch-days: 5
