#! /usr/bin/env bash

pushd "$(dirname "$0")" > /dev/null
set -e

[[ -n "$1" ]] || { echo "Usage: $0 <version>"; exit 1; }

while IFS= read -r -d '' entry
do
    echo "$entry"
    line=$(grep -n -m1 "version" "$entry" | cut -d: -f2)
    current=$(echo "${line}" | awk -F'"' '{print $2}')
    sed -i.bak "s/$current/$1/g" "$entry" && rm "$entry.bak"
done < <(find . -mindepth 2 -name Cargo.toml -print0)

popd > /dev/null
