#! /bin/bash

cd "$(dirname "$0")"
set -e

[[ -n "$1" ]] || { echo "Usage: $0 <version>"; exit 1; }

for entry in `find . -mindepth 2 -name Cargo.toml -print`; do
    echo $entry
    line=$(grep -n -m1 "version" $entry | cut -d: -f2)
    CURRENT=$(echo ${line} | awk -F'"' '{print $2}')
    sed -i "" "s/$CURRENT/$1/g" $entry
done
