name: Lint GitHub Actions workflows
on:
  push:
    branches: ["main"]
    paths: [".github/**"]
  pull_request:
    paths: [".github/**"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    uses: mozilla/actions/.github/workflows/actionlint.yml@b6b1031d2072eb8c2b181887cb5e194ebcc5caab # v1.0.4
    permissions:
      contents: read
      security-events: write # Required for zizmor to upload SARIF results.
