name: Lint GitHub Actions workflows
on:
  push:
    branches: ["main"]
    paths: [".github/**"]
  pull_request:
    paths: [".github/**"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    uses: mozilla/actions/.github/workflows/actionlint.yml@66a0665e8ea4b3ba7a8fd010b791f56625d6a932 # v1.0.11
    permissions:
      contents: read
      security-events: write # Required for zizmor to upload SARIF results.
