name: Deny
on:
  workflow_dispatch:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deny:
    uses: mozilla/actions/.github/workflows/deny.yml@66a0665e8ea4b3ba7a8fd010b791f56625d6a932 # v1.0.11
