name: Machete
on:
  workflow_dispatch:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  machete:
    uses: mozilla/actions/.github/workflows/machete.yml@fdbc149234005e066f838be6bb654dfb0b570cee # TEST mozilla/actions#127 - DO NOT MERGE
