name: Machete
on:
  workflow_dispatch:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  machete:
    uses: mozilla/actions/.github/workflows/machete.yml@312d300af3fb2b6551389bf1cb40b10e86294ec2 # v1.1.4
