name: Check README.md
on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  readme:
    name: Check README.md
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: mozilla/actions/rust@66a0665e8ea4b3ba7a8fd010b791f56625d6a932 # v1.0.11
        with:
          tools: cargo-readme
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          cd mtu # Only works for this crate currently.
          # TODO: cargo-readme doesn't support workspaces: https://github.com/webern/cargo-readme/issues/81
          # Leaving this here so we remember to fix it later.
          # cargo readme -o /tmp/README.md
          # diff -u README.md /tmp/README.md
