name: Format
on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format:
    uses: mozilla/actions/.github/workflows/rustfmt.yml@bf3fb2950385cdbf80d0248db988d39096963755 # v2.0.0
