name: Format
on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format:
    uses: mozilla/actions/.github/workflows/rustfmt.yml@32d84c77ea1bb513afbd253f94f67ae138b7d8be # v2.0.10
