name: Format
on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format:
    uses: mozilla/actions/.github/workflows/rustfmt.yml@2152d1412122b04d838d6341aa3b4d6160b3de32 # v2.0.5
