name: SBOM

on:
  release:
    types: [published]
  workflow_dispatch:

permissions: {}

jobs:
  sbom:
    uses: mozilla/actions/.github/workflows/sbom.yml@32d84c77ea1bb513afbd253f94f67ae138b7d8be # v2.0.10
    permissions:
      actions: read # Required by anchore/sbom-action to read workflow run context.
      contents: write # Required to upload the SBOM as a release asset.
