name: SBOM

on:
  release:
    types: [published]
  workflow_dispatch:

permissions: {}

jobs:
  sbom:
    uses: mozilla/actions/.github/workflows/sbom.yml@7cca521fd0ace71bc6ee830c4a98297023e3402b # v1.1.18
    permissions:
      actions: read # Required by anchore/sbom-action to read workflow run context.
      contents: write # Required to upload the SBOM as a release asset.
