name: SBOM

on:
  release:
    types: [published]
  workflow_dispatch:

permissions: {}

jobs:
  sbom:
    uses: mozilla/actions/.github/workflows/sbom.yml@96ce92daf6ecffbe02728649f25f32a15eba543e # v2.0.2
    permissions:
      actions: read # Required by anchore/sbom-action to read workflow run context.
      contents: write # Required to upload the SBOM as a release asset.
