name: Check semver
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  semver:
    name: Check semver
    runs-on: ubuntu-24.04
    steps:
      - uses: mozilla/actions/semver@dbead646641c6d53d4d6f98beeb69f8fdec65513 # v2.0.4
        with:
          package: mtu
