name: Check semver
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  semver:
    name: Check semver
    runs-on: ubuntu-24.04
    steps:
      - uses: mozilla/actions/semver@2152d1412122b04d838d6341aa3b4d6160b3de32 # v2.0.5
        with:
          package: mtu
